server:
  port: 80

  #spring:
  # profiles:
  #  active: dev  #区域名
spring:
  application:
    name: cloud-consumer-feign-order80

eureka:
  client:
    # 表示是否将自己注册进注册中心，默认为true
    register-with-eureka: true
    # 表示是否从EurekaServer抓取已有的注册信息，默认为true，单节点无所谓，集群必须为true，才能配合ribbon使用负载均衡
    fetch-registry: true
    #注册中心服务地址，你想把这个服务端注册到哪个注册中心，就写哪个注册中心地址，也可以主策到多个注册中心，中间用“，”隔开
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: Feign_Order80 #为客户端设置id/主机名称
    prefer-ip-address: true #访问路径可以显示Ip地址