server:
  port: 8002


  #spring:
  # profiles:
  #  active: dev  #区域名
spring:
  application:
    name: cloud-payment-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lianxi?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  rocket-api:
    base-register-path: /interface-ui
    config-enabled: true #开启配置功能
    #view-enabled: true #启用UI控制界面/interface-ui,用于生产环境的安全配置，默认为true 测试环境可配置
    #map-underscore-to-camel-case: true #驼峰自动转换配置，默认为true
#通过actuator进行spring boot应用监控
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

eureka:
  client:
    # 表示是否将自己注册进注册中心，默认为true
    register-with-eureka: true
    # 表示是否从EurekaServer抓取已有的注册信息，默认为true，单节点无所谓，集群必须为true，才能配合ribbon使用负载均衡
    fetch-registry: true
    #注册中心服务地址，你想把这个服务端注册到哪个注册中心，就写哪个注册中心地址，也可以主策到多个注册中心，中间用“，”隔开
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: payment8003 #为客户端设置id/主机名称
    prefer-ip-address: true #访问路径可以显示Ip地址